# Generated by Django 4.0.2 on 2022-02-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_problems_problemoptions_archivedcustomers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcustomers',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
