# Generated by Django 4.0.2 on 2022-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_archivedcustomers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcustomers',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
