# Generated by Django 4.0.2 on 2022-02-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_archivedcustomers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='date_Join',
        ),
    ]
