# Generated by Django 4.0.2 on 2022-02-23 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customermodel_date_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='date_Join',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
